Metrics/MethodLength: 
  Max: 50

convention:Style/Documentation:
  Enabled: false

convention:Style/FrozenStringLiteralComment:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Metrics/BlockLength:
  Max: 100

Metrics/AbcSize:
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 20

Style/StringLiterals:
  Enabled: false
  