Metrics/MethodLength: 
  Length: 30

convention:Style/Documentation:
  Enabled: false

convention:Style/FrozenStringLiteralComment:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Metrics/BlockLength:
  Length: 100