convention:Style/Documentation:
  Enabled: false

convention:Style/FrozenStringLiteralComment:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/RedundantBegin:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

Metrics/BlockLength:
  Max: 100

Metrics/AbcSize:
  Max: 100

Metrics/CyclomaticComplexity:
  Max: 20

Metrics/MethodLength: 
  Max: 50
  